<?php
/**
 * UI string translations for header navigation, mobile menu and footer.
 *
 * Page body content lives in /parts/{base}-{lang}.php. These strings cover
 * the shared chrome rendered by header.php and footer.php.
 *
 * @package Ferroxa
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function ferroxa_strings() {
	return array(

		'en' => array(
			// Primary nav.
			'nav_home'        => 'Home',
			'nav_about'       => 'About',
			'nav_products'    => 'Products',
			'nav_contact'     => 'Contact',
			'nav_blog'        => 'Blog',
			'nav_whatwedo'    => 'What We Do',
			// Mega-menu categories.
			'cat_ferrous'     => 'Ferrous Metals',
			'cat_nonferrous'  => 'Non-Ferrous Metals',
			'cat_precious'    => 'Precious Metals',
			'sub_semifinished'=> 'Semi-Finished',
			'sub_flat'        => 'Flat',
			'sub_long'        => 'Long',
			// Products.
			'p_steel_billets' => 'Steel Billets',
			'p_steel_slabs'   => 'Steel Slabs',
			'p_hrc'           => 'Hot-Rolled Coil (HRC)',
			'p_crc'           => 'Cold-Rolled Coil (CRC)',
			'p_galvanized'    => 'Galvanized Steel (GI/GL)',
			'p_plates'        => 'Plates',
			'p_rebar'         => 'Rebar',
			'p_wire_rods'     => 'Wire Rods',
			'p_structural'    => 'Structural Steel',
			'p_copper'        => 'Copper',
			'p_aluminum'      => 'Aluminum',
			'p_zinc'          => 'Zinc',
			'p_gold'          => 'Raw Gold',
			'p_gold_mobile'   => 'Non-Manufactured Gold',
			'p_silver'        => 'Silver',
			// Footer.
			'footer_tagline'      => 'Connecting Markets, Building Trust',
			'footer_quicklinks'   => 'Quick Links',
			'footer_about_us'     => 'About Us',
			'footer_our_products' => 'Our Products',
			'footer_prod_1'       => 'Ferrous Metals',
			'footer_prod_2'       => 'Non-Ferrous Metals',
			'footer_prod_3'       => 'Precious Metals',
			'footer_contact_info' => 'Contact Information',
			'footer_hours'        => 'Mon - Fri: 9:00 AM - 6:00 PM (SGT)',
			'footer_rights'       => 'All rights reserved.',
			'footer_privacy'      => 'Privacy Policy',
			'footer_terms'        => 'Terms &amp; Conditions',
			'footer_cookie'       => 'Cookie Policy',
		),

		'ar' => array(
			'nav_home'        => 'الرئيسية',
			'nav_about'       => 'حول',
			'nav_products'    => 'المنتجات',
			'nav_contact'     => 'اتصل',
			'nav_blog'        => 'المدونة',
			'nav_whatwedo'    => 'ما نفعله',
			'cat_ferrous'     => 'المعادن الحديدية',
			'cat_nonferrous'  => 'المعادن غير الحديدية',
			'cat_precious'    => 'المعادن الثمينة',
			'sub_semifinished'=> 'شبه منتهية',
			'sub_flat'        => 'مسطحة',
			'sub_long'        => 'طويلة',
			'p_steel_billets' => 'سبائك الصلب',
			'p_steel_slabs'   => 'ألواح الصلب',
			'p_hrc'           => 'لفائف مدرفلة على الساخن',
			'p_crc'           => 'لفائف مدرفلة على البارد',
			'p_galvanized'    => 'صلب مجلفن',
			'p_plates'        => 'ألواح',
			'p_rebar'         => 'حديد التسليح',
			'p_wire_rods'     => 'قضبان سلكية',
			'p_structural'    => 'صلب هيكلي',
			'p_copper'        => 'نحاس',
			'p_aluminum'      => 'ألومنيوم',
			'p_zinc'          => 'زنك',
			'p_gold'          => 'الذهب الخام',
			'p_gold_mobile'   => 'ذهب غير مصنع',
			'p_silver'        => 'فضة',
			'footer_tagline'      => 'ربط الأسواق، وبناء الثقة',
			'footer_quicklinks'   => 'روابط سريعة',
			'footer_about_us'     => 'من نحن',
			'footer_our_products' => 'منتجاتنا',
			'footer_prod_1'       => 'المعادن الحديدية',
			'footer_prod_2'       => 'المعادن الغير حديدية',
			'footer_prod_3'       => 'المعادن الثمينة',
			'footer_contact_info' => 'معلومات الاتصال',
			'footer_hours'        => 'الأحد - الجمعة : 9:00 - 18:00',
			'footer_rights'       => 'جميع الحقوق محفوظة.',
			'footer_privacy'      => 'سياسة الخصوصية',
			'footer_terms'        => 'الشروط والأحكام',
			'footer_cookie'       => 'سياسة ملفات تعريف الارتباط',
		),

		'fr' => array(
			'nav_home'        => 'Accueil',
			'nav_about'       => 'À propos',
			'nav_products'    => 'Produits',
			'nav_contact'     => 'Contact',
			'nav_blog'        => 'Blog',
			'nav_whatwedo'    => 'Ce Que Nous Faisons',
			'cat_ferrous'     => 'Métaux Ferreux',
			'cat_nonferrous'  => 'Métaux Non-Ferreux',
			'cat_precious'    => 'Métaux Précieux',
			'sub_semifinished'=> 'Semi-Finis',
			'sub_flat'        => 'Plats',
			'sub_long'        => 'Longs',
			'p_steel_billets' => "Billettes d'Acier",
			'p_steel_slabs'   => "Brammes d'Acier",
			'p_hrc'           => 'Bobines Laminées à Chaud (HRC)',
			'p_crc'           => 'Bobines Laminées à Froid (CRC)',
			'p_galvanized'    => 'Acier Galvanisé (GI/GL)',
			'p_plates'        => 'Plaques',
			'p_rebar'         => "Barres d'Armature",
			'p_wire_rods'     => 'Fils Machine',
			'p_structural'    => 'Acier de Structure',
			'p_copper'        => 'Cuivre',
			'p_aluminum'      => 'Aluminium',
			'p_zinc'          => 'Zinc',
			'p_gold'          => 'Or Brut',
			'p_gold_mobile'   => 'Or Non-Manufacturé',
			'p_silver'        => 'Argent',
			'footer_tagline'      => 'Relier les marchés, bâtir la confiance',
			'footer_quicklinks'   => 'Liens Rapides',
			'footer_about_us'     => 'À Propos',
			'footer_our_products' => 'Nos Produits',
			'footer_prod_1'       => 'Cuivre',
			'footer_prod_2'       => 'Argent',
			'footer_prod_3'       => 'Or Brut',
			'footer_contact_info' => 'Informations de Contact',
			'footer_hours'        => 'Dim - Jeu: 9:00 - 18:00',
			'footer_rights'       => 'Tous droits réservés.',
			'footer_privacy'      => 'Politique de Confidentialité',
			'footer_terms'        => 'Termes et Conditions',
			'footer_cookie'       => 'Politique des Cookies',
		),
	);
}
